parameters:
    ezplatform_restv3.input.parser.ContentCreate.class: EzSystems\Restv3\Core\Input\Parser\ContentCreate
    ezplatform_restv3.input.parser.ContentUpdate.class: EzSystems\Restv3\Core\Input\Parser\ContentUpdate
    ezplatform_restv3.input.parser.LocationCreate.class: EzSystems\Restv3\Core\Input\Parser\LocationCreate

services:

    ezplatform_restv3.input.parser.ContentCreate:
        parent: ezpublish_rest.input.parser
        class: '%ezplatform_restv3.input.parser.ContentCreate.class%'
        arguments:
            - '@ezpublish.api.service.content'
            - '@ezpublish.api.service.content_type'
            - '@ezpublish.api.service.user'
            - '@ezpublish_rest.field_type_parser'
            - '@ezplatform_restv3.input.parser.LocationCreate'
            - '@ezpublish_rest.parser_tools'
        tags:
            - { name: ezpublish_rest.input.parser, mediaType: application/vnd.ez.api.ContentCreate; version=2.0 }

    ezplatform_restv3.input.parser.ContentUpdate:
        parent: ezpublish_rest.input.parser
        class: '%ezplatform_restv3.input.parser.ContentUpdate.class%'
        arguments:
            - '@ezpublish.api.service.content'
            - '@ezpublish.api.service.location'
            - '@ezpublish_rest.field_type_parser'
        tags:
            - { name: ezpublish_rest.input.parser, mediaType: application/vnd.ez.api.ContentUpdate; version=2.0 }

    ezplatform_restv3.input.parser.LocationCreate:
        parent: ezpublish_rest.input.parser
        class: '%ezplatform_restv3.input.parser.LocationCreate.class%'
        arguments:
            - '@ezpublish.api.service.location'
            - '@ezpublish.api.service.url_alias'
            - '@ezpublish_rest.parser_tools'
        tags:
            - { name: ezpublish_rest.input.parser, mediaType: application/vnd.ez.api.LocationCreate; version=2.0 }
